name: Scala CI

on:
  push:
    branches: [ master, feature/github_action ]
  pull_request:
    branches: [ master, feature/github_action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
