name: Scala CI

on:
  push:
    branches: [ master, feature/github_action ]
# temporary disable
#  pull_request:
#    branches: [ master, feature/github_action ]
#    paths: ['src/**', 'test/**']
  release:
    types: [published, created, edited]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
