name: Scala tests

on:
  push:
    branches: [ master, main]
  pull_request:
    branches: [ master, main ]
    paths: ['src/**', 'test/**']
  release:
    types: [published, created, edited]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        java:
        - adopt@1.8
    steps:
    - uses: actions/checkout@v2
    - name: Set Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: sbt test
